### PR TITLE
Feature/i-48-repl_edits

### PR DESCRIPTION
**Pull request by sutterj**
I added more test cases for the REPL and fixed the calling of the display functions.  @delgrecoj what data type is dataframe?  I don't know what to pass in the test case for the REPL.  I know that this can't be run yet without commenting out a bunch of stuff, but it would be helpful if you could all look it over to check for any mistakes.

### CODE REVIEW

**Comment by delgrecoj** [comment]
The dataframe is of a type defined by the `pandas` library... testing the REPL functionality should not touch the dataframe in any way though... only the query functions should ever touch the dataframe, and only read from it at that.

**Comment by sutterj** [comment]
@delgrecoj I have to pass something to the query function in order to test the repl.  I don't need output, but I have to have a parameter to pass.  Would it work to pass a string as a place holder?

**Comment by delgrecoj** [comment]
@sutterj, what you need to pass to the query functions depends on which query function is being called... all of them require the dataframe as the first argument, which should be available to the system after the `parse_csv_into_dataframe` function is called from `accelegator.py`.  The function signatures for the query functions are all available in the branch for issue #31, and to answer your question, passing any of them just a string argument will not work.

The REPL functionality must be testable in isolation from the other modules of the system.

**Comment by sutterj** [comment]
It passes if you comment out all of the function calls in repl.py.  There is nothing to test if you can't call the functions because each of the repl commands requires arguments.

**Comment by sutterj** [comment]
@delgrecoj @yeeunmariakim @eltmanm I restructured the files so that they are not dependant on the functions to pass the test suite.  Please let me know if there are any other changes that need to be made

**Pull request merged**
