### PR TITLE
adding flake8 test case [issue 8]

### PR DESCRIPTION
**Pull request by lylet-AC**
I added the flake8 testcase so now we can read the python files.

### CODE REVIEW

**Comment by yeeunmariakim** [comment]
@lylet-AC it looks like perhaps you added a new file instead of renaming the old one? I see 2 files now.

**Comment by lylet-AC** [comment]
Yeah, I'm taking care of it in a sec.  I thought it might remove it but I see the `git rm` command now and Ill also push the README to finish this.

**Comment by lylet-AC** [comment]
It should be good now

**Comment by yeeunmariakim** [comment]
@lylet-AC the install command is not in Markdown format. I think you meant to write backticks, not single quotes.

**Comment by yeeunmariakim** [comment]
@lylet-AC thanks so much for making all those revisions!

**Pull request merged**
