### PR TITLE
travis and coveralls

### PR DESCRIPTION
**Pull request by Andre-Bryan**
done with travis and coveralls

### CODE REVIEW

**Comment by yeeunmariakim** [comment]
@Andre-Bryan does this display the test coverage in the README?

**Comment by Andre-Bryan** [comment]
yes it will just like the last lab

**Comment by Andre-Bryan** [comment]
The build will fail until a requirements.txt file is made

**Comment by yeeunmariakim** [comment]
@Andre-Bryan can you create the requirements.txt file?

**Pull request merged**
