### PR TITLE
adding the test cases for gensim

### PR DESCRIPTION
**Pull request by toccinAC**
These are the test cases that I wrote for the NLP portion.

### CODE REVIEW

**Comment by toccinAC** [comment]
I don't know why this is failing, I think that it is because we don't have gensim as a requirement somewhere.

**Comment by burrowss** [comment]
Ill add it to the travis requirements

**Comment by burrowss** [comment]
Does pyLDAvis have to be installed too?

**Comment by toccinAC** [comment]
It is because things in the accelegator_NLP.py are not in the requirements.

**Pull request merged**
